[workspace]
members = [".", "xtask"]
resolver = "2"

[package]
name = "mastering_guide"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
nih_plug = { git = "https://github.com/audio-forge-rs/nih-plug.git", branch = "master" }
nih_plug_egui = { git = "https://github.com/audio-forge-rs/nih-plug.git", branch = "master" }
atomic_refcell = "0.1"
realfft = "3.3"
ebur128 = "0.1"
crossbeam-queue = "0.3"
atomic_float = "1.0"
num-complex = "0.4"
serde = { version = "1", features = ["derive"] }

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
strip = true
